### ISSUE TITLE
Wrong unit for pressure?

### ISSUE THREAD

**Issue by patkan** [lichtteil/local_luftdaten#12]
I upgraded to the new release that includes BMP and just realized that I probably made a mistake in my PR.

As an orientation I took the existing implementation for BME280 sensors and set the unit of the pressure to mbar. It seems to me, however, the sensor reports the values in Pa.
I would prepare a Pull Request with changed units for both the sensors that I introduced and the BME280 for you to review.

**Comment by lichtteil** [comment]
Good catch, thank you! Didn't notice that because in my template sensor I correctly convert it to hPa :)
