### ISSUE TITLE
Plantower sensor support

### ISSUE THREAD

**Issue by Jabol86** [lichtteil/local_luftdaten#18]
Hi,
there would be a chance to add Plantower sensor support, e.g. PMS7003.
An example json file is:

`{"software_version": "**********", "age":"0", "sensordatavalues":[{"value_type":"PMS_P0","value":"22.00"},{"value_type":"PMS_P1","value":"38.40"},{"value_type":"PMS_P2","value":"31.60"},{"value_type":"BME280_temperature","value":"20.01"},{"value_type":"BME280_humidity","value":"51.85"},{"value_type":"BME280_pressure","value":"100893.76"},{"value_type":"samples","value":"1744880"},{"value_type":"min_micro","value":"78"},{"value_type":"max_micro","value":"89701"},{"value_type":"signal","value":"-48"}]}`

PMS_P0 = PM1
PMS_P1 = PM10
PMS_P2 = PM2,5

Please ;)

PS. 
I also have a problem with showing the pressure by BME280, I don't know how to change it despite the instructions; /

**Comment by lichtteil** [comment]
Hi @Jabol86, thanks for your example JSON. I will try to integrate the sensor on the weekend. You can open another issue where we can have a look at your BME pressure problem.
