### ISSUE TITLE
Honeywell Particulate Sensor is not Supported > HPM_P1, HPM_P2`

### ISSUE THREAD

**Issue by thoughtleader** [lichtteil/local_luftdaten#27]
"sensordatavalues": [
    {
      "value_type": "HPM_P1",
      "value": "26.50"
    },
    {
      "value_type": "HPM_P2",
      "value": "24.75"
    },

**Comment by lichtteil** [comment]
@thoughtleader Thank you for the sample. I updated the integration, it should work now :) Let me know if you run into problems.
