### ISSUE TITLE
No value returned after upgrade to HA 2021.6.3

### ISSUE THREAD

**Issue by zigomatichub** [lichtteil/local_luftdaten#36]
Hello lichtteil,
Since the last update , local luftdaten show NAN on all values. I still see the value localy and IP address didn't change.
I don't have any logs issues reported.  Reinstall + Restart don't help. 

Version installed is 2.0.0 via HACS

Can you help ?

Do you think there is a link with something change in HA because I see this https://github.com/home-assistant/core/pull/50365  ?

**Comment by Joe3n** [comment]
Hi,
the update 2.0 has breaking changes. My guess is you didn‘t do the migration like described here https://github.com/lichtteil/local_luftdaten/issues/33#issuecomment-842185598. With the 2.0 update the entityID changed. Please try it and give some feedback ;)

**Comment by zigomatichub** [comment]
Thank you @JoachimEngelmann
Indeed, Newly entities was created. I managed to put back with your explaination.
