### ISSUE TITLE
Suport for Long term statistics

### ISSUE THREAD

**Issue by Nizm0** [lichtteil/local_luftdaten#38]
Hi
Can you add suport fot long term statistics from last HA update?

**Comment by lichtteil** [comment]
Hi, yes, I'm reading the documentation right in this moment :)

**Comment by ddppddpp** [comment]
I'm using an approach similar to your integration to get data from my own sensor without going to the cloud. I'm facing the blocker that template sensors don't support the state_class property. Any ideas how to go around this?
