### ISSUE TITLE
Migrate to native_value/native_unit_of_measurement

### ISSUE THREAD

**Issue by lichtteil** [lichtteil/local_luftdaten#39]
https://developers.home-assistant.io/blog/2021/08/12/sensor_temperature_conversion
https://developers.home-assistant.io/docs/core/entity/sensor

**Comment by otiswrx** [comment]
Hello, 

Is there any plan to implement this? Since updating to 2022.7.1 my temperature sensor defaults to '°C' and automations no longer work because I use '°F'

Thanks in advance!

**Comment by lichtteil** [comment]
I'm currently quite busy but I will try to work on that soon. Maybe till then you can use a template sensor to calculate the fahrenheit value and use that in your automations.

Maybe there is also someone faster than me who could provide a pull request!?

**Comment by lichtteil** [comment]
Done via #49
