### ISSUE TITLE
Specify port number for the host?

### ISSUE THREAD

**Issue by sverd** [lichtteil/local_luftdaten#42]
Is it possible to specify a certain port for the specified host? I would like to connect the luftdaten sensor to a separate network using a esp repeater/AP. When a port could be specified some portmapping rules would do the job but currently I'm unable to get to the sensor.

**Comment by lichtteil** [comment]
Hi, can you please try to add the port to the host configuration?
E.g.: `host: 192.168.0.10:1234`

**Comment by sverd** [comment]
Hi,
sorry it took a while. I tried your suggestion and it does seem to work now. I already tried this approach before posting the original question and back then it surely did not work. Probably something was wrong with my network settings (I changed them quite a bit and learned a lot since then). Sorry for any inconvenience and thanks for responding. I really like your project!
