### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by finintra** [lichtteil/local_luftdaten#43]
Logger: custom_components.local_luftdaten.sensor
Source: custom_components/local_luftdaten/sensor.py:186
Integration: local_luftdaten (documentation, issues)
First occurred: 01:40:21 (900 occurrences)
Last logged: 09:07:24

REST result could not be parsed as JSON

**Comment by lichtteil** [comment]
Hi @finintra,
can you please check if you can see the json when opening it in your browser? Put the ip address of your sensor in here:
`http://192.168.0.123/data.json`.
