### ISSUE TITLE
WARNING (MainThread) [custom_components.local_luftdaten.sensor] REST request timeout

### ISSUE THREAD

**Issue by xHuubx** [lichtteil/local_luftdaten#54]
I installed the pluging through HACS, I added the lines in configuration.yal, see first lines below:

' ## LuftDaten
  - platform: local_luftdaten
    host: 192.168.XX.11
    scan_interval: 180
    name: Fijnstofsensor
    monitored_conditions:
      - SDS_P1
      - SDS_P2
      - BME280_temperature
      - BME280_pressure
      - BME280_humidity
      - signal'
     
If I go to 192.168.XX.11/data.jason than I can also see the raw data. 
In HA I do not see any data, if I look in the logs I see:

2023-02-20 13:07:05.610 WARNING (MainThread) [homeassistant.components.sensor] Updating local_luftdaten sensor took longer than the scheduled update interval 0:03:00
2023-02-20 13:07:05.626 WARNING (MainThread) [custom_components.local_luftdaten.sensor] REST request timeout

Can someone help me out please?

**Comment by lichtteil** [comment]
Hi @xHuubx,
did you resolve the issue? It looks to me like there is some network problem between your Home Assistant instance and the sensor node.

**Comment by xHuubx** [comment]
Yes, it was resolved, had to set my FW right. You may close the ticket.


Op ma 12 jun. 2023 om 16:52 schreef Mario ***@***.***>
