### ISSUE TITLE
After update to Homeassistant i get this error and data is not longer shown 

### ISSUE THREAD

**Issue by edegraaff** [lichtteil/local_luftdaten#65]
Home Assistant version 2024.11.3

Logger: homeassistant.util.loop
Bron: util/loop.py:136
Eerst voorgekomen: 15:57:46 (1 gebeurtenissen)
Laatst gelogd: 15:57:46

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f0c9cd71ad0>,) inside the event loop by integration 'luftdaten' at homeassistant/components/luftdaten/__init__.py, line 41: await sensor_community.get_data() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+luftdaten%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/luftdaten/__init__.py", line 60, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data return await self.update_method() File "/usr/src/homeassistant/homeassistant/components/luftdaten/__init__.py", line 41, in async_update await sensor_community.get_data()

**Comment by lichtteil** [comment]
This issue comes with the official luftdaten integration of Home Assistant Core and not with this custom integration for local polling. There is already an issue that you can find here: https://github.com/home-assistant/core/issues/125727

**Comment by edegraaff** [comment]
> This issue comes with the official luftdaten integration of Home Assistant Core and not with this custom integration for local polling. There is already an issue that you can find here: [home-assistant/core#125727](https://github.com/home-assistant/core/issues/125727)

Thanks for your response, after a few reboots at least the data is shown again ..
