### ISSUE TITLE
HTU21D sensor

### ISSUE THREAD

**Issue by 22MarioZ** [lichtteil/local_luftdaten#7]
Hello!

The HTU21D Sensor have the following structure:
`{
   "software_version":"NRZ-2020-130-B5",
   "age":"174",
   "sensordatavalues":[
      {
         "value_type":"SDS_P1",
         "value":"11.50"
      },
      {
         "value_type":"SDS_P2",
         "value":"6.22"
      },
      {
         "value_type":"HTU21D_temperature",
         "value":"30.15"
      },
      {
         "value_type":"HTU21D_humidity",
         "value":"14.55"
      },
      {
         "value_type":"samples",
         "value":"3190747"
      },
      {
         "value_type":"min_micro",
         "value":"55"
      },
      {
         "value_type":"max_micro",
         "value":"20120"
      },
      {
         "value_type":"signal",
         "value":"-76"
      }
   ]
}`

Can you update the Component?

Thank you.

**Comment by lichtteil** [comment]
Hi @22MarioZ,
can you select the dev branch in your HACS configuration and test it (select `dev`, press `Update`, restart Home Assistant)? 

<img width="1216" alt="Screenshot 2020-04-16 at 00 01 46" src="https://user-images.githubusercontent.com/1080718/79393508-c585c180-7f75-11ea-9fea-ef15f5b39f8b.png">

**Comment by 22MarioZ** [comment]
Hi,

Installed and is working. I can get the data in the HA.

Thank you.

**Comment by lichtteil** [comment]
Closed via https://github.com/lichtteil/local_luftdaten/pull/9
